app <- ShinyDriver$new("../../")
app$snapshotInit("BasicGitWorkflow")

app$setInputs(sidebarCollapsed = FALSE)
app$setInputs(tabs = "workflow")
app$snapshot()
app$setInputs(`basic_git_workflow_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`basic_git_workflow_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`basic_git_workflow_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`basic_git_workflow_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`basic_git_workflow_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`basic_git_workflow_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`basic_git_workflow_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`basic_git_workflow_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`basic_git_workflow_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`basic_git_workflow_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(`basic_git_workflow_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(`basic_git_workflow_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(`basic_git_workflow_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(`basic_git_workflow_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(`basic_git_workflow_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(`basic_git_workflow_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(`basic_git_workflow_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(`basic_git_workflow_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(next_button = "click")
app$snapshot()
