app <- ShinyDriver$new("../../")
app$snapshotInit("IntroductionToBranching")

app$setInputs(sidebarCollapsed = FALSE)
app$setInputs(sidebarItemExpanded = "4.BasicGitBranching")
app$snapshot()
app$setInputs(tabs = "intro_branching")
app$snapshot()
app$setInputs(`basic_branching_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`basic_branching_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`basic_branching_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`basic_branching_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(`basic_branching_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(`basic_branching_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(next_button = "click")
app$snapshot()
