app <- ShinyDriver$new("../../")
app$snapshotInit("IntroductionToMerging")

app$setInputs(sidebarCollapsed = FALSE)
app$setInputs(sidebarItemExpanded = "4.BasicGitBranching")
app$snapshot()
app$setInputs(tabs = "merging")
app$snapshot()
app$setInputs(`intro_merging_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-next_button` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-previous_button` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-next_button2` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-next_button2` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-next_button2` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-next_button2` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-next_button2` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-next_button2` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-next_button2` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-next_button2` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-previous_button2` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-previous_button2` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-previous_button2` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-previous_button2` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-previous_button2` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-previous_button2` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-previous_button2` = "click")
app$snapshot()
app$setInputs(`intro_merging_ui_1-previous_button2` = "click")
app$snapshot()
app$setInputs(next_button = "click")
app$snapshot()
