app <- ShinyDriver$new("../../")
app$snapshotInit("NavBar")

app$setInputs(sidebarCollapsed = FALSE)
app$snapshot()
app$setInputs(next_button = "click")
app$snapshot()
app$setInputs(previous_button = "click")
app$snapshot()
app$setInputs(tabs = "workflow")
app$snapshot()
app$setInputs(next_button = "click")
app$snapshot()
app$setInputs(next_button = "click")
app$snapshot()
app$setInputs(previous_button = "click")
app$snapshot()
app$setInputs(sidebarItemExpanded = "3.BasicGitCommands")
app$setInputs(tabs = "untracked")
app$snapshot()
app$setInputs(next_button = "click")
app$snapshot()
app$setInputs(previous_button = "click")
app$snapshot()
app$setInputs(sidebarItemExpanded = "4.BasicGitBranching")
app$setInputs(tabs = "merging")
app$setInputs(next_button = "click")
app$snapshot()
app$setInputs(previous_button = "click")
app$snapshot()
