app <- ShinyDriver$new("../../")
app$snapshotInit("TrackingChanges")

app$setInputs(sidebarCollapsed = FALSE)
app$setInputs(sidebarItemExpanded = "3.BasicGitCommands")
app$snapshot()
app$setInputs(tabs = "commit")
app$snapshot()
app$setInputs(`tracking_changes_ui_1-next_button1` = "click")
app$snapshot()
app$setInputs(`tracking_changes_ui_1-next_button1` = "click")
app$snapshot()
app$setInputs(`tracking_changes_ui_1-next_button1` = "click")
app$snapshot()
app$setInputs(`tracking_changes_ui_1-previous_button1` = "click")
app$snapshot()
app$setInputs(`tracking_changes_ui_1-previous_button1` = "click")
app$snapshot()
app$setInputs(`tracking_changes_ui_1-previous_button1` = "click")
app$snapshot()
app$setInputs(`tracking_changes_ui_1-next_button2` = "click")
app$snapshot()
app$setInputs(`tracking_changes_ui_1-next_button2` = "click")
app$snapshot()
app$setInputs(`tracking_changes_ui_1-next_button2` = "click")
app$snapshot()
app$setInputs(`tracking_changes_ui_1-previous_button2` = "click")
app$snapshot()
app$setInputs(`tracking_changes_ui_1-previous_button2` = "click")
app$snapshot()
app$setInputs(`tracking_changes_ui_1-previous_button2` = "click")
app$snapshot()
app$setInputs(next_button = "click")
app$snapshot()
